version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: swift
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /landing-page
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
