#!/bin/bash
# Commit the appcast a release just generated back to the default branch so
# landing-page/appcast.xml in git matches what was deployed. Without this the
# git copy goes stale, deploy-landing-page.yml would re-publish an old feed on
# the next landing-page change, and the appcast-contract test cannot demand
# freshness (APPCAST_REQUIRE_LATEST=1).
#
# Runs in release.yml after the live feed has been deployed, so it is
# deliberately NON-FATAL: a failure here must never fail a release that is
# already out (verify-release depends on the job). It tries a direct push to
# the branch first; if that is rejected (branch protection) it pushes a
# `release/appcast-v<version>` branch and opens a PR when `gh` + GH_TOKEN are
# available, emitting a ::warning:: either way.
#
# Usage: scripts/ci-commit-appcast.sh <appcast.xml> <version>
#   REPO_URL       clone/push URL (default: token URL for GITHUB_REPOSITORY using GH_TOKEN)
#   TARGET_BRANCH  default main
#   APPCAST_DEST   path inside the repo (default landing-page/appcast.xml)
#   SKIP_CI        1 (default) appends "[skip ci]" so the commit does not burn a full macOS CI run
#   WORK_DIR       scratch dir (default mktemp)
# Exit 0 in every handled case; 2 only for bad usage.

set -euo pipefail

APPCAST="${1:-}"; VERSION="${2:-}"
[ -n "$APPCAST" ] && [ -n "$VERSION" ] || { echo "usage: $0 <appcast.xml> <version>" >&2; exit 2; }
[ -f "$APPCAST" ] || { echo "usage: $0: no such appcast file: $APPCAST" >&2; exit 2; }
VERSION="${VERSION#v}"
TARGET_BRANCH="${TARGET_BRANCH:-main}"
APPCAST_DEST="${APPCAST_DEST:-landing-page/appcast.xml}"
SKIP_CI="${SKIP_CI:-1}"
if [ -z "${REPO_URL:-}" ]; then
  [ -n "${GH_TOKEN:-}" ] && [ -n "${GITHUB_REPOSITORY:-}" ] || { echo "usage: $0: set REPO_URL, or GH_TOKEN + GITHUB_REPOSITORY" >&2; exit 2; }
  REPO_URL="https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
fi
WORK_DIR="${WORK_DIR:-$(mktemp -d "${TMPDIR:-/tmp}/appcast-commit.XXXXXX")}"
mkdir -p "$WORK_DIR"
APPCAST_ABS="$(cd "$(dirname "$APPCAST")" && pwd)/$(basename "$APPCAST")"

warn() { echo "::warning::commit-appcast v${VERSION}: $*"; }

echo "==> Cloning ${TARGET_BRANCH} to commit ${APPCAST_DEST} for v${VERSION}"
if ! git clone --quiet --depth 1 --branch "$TARGET_BRANCH" "$REPO_URL" "$WORK_DIR/repo" 2>"$WORK_DIR/clone.err"; then
  warn "could not clone ${TARGET_BRANCH}: $(tail -1 "$WORK_DIR/clone.err" | sed -E 's#https://[^@]+@#https://***@#'). The git copy of the appcast is now stale; copy the released appcast into ${APPCAST_DEST} by hand."
  exit 0
fi
cd "$WORK_DIR/repo"
mkdir -p "$(dirname "$APPCAST_DEST")"
cp "$APPCAST_ABS" "$APPCAST_DEST"
if git diff --quiet -- "$APPCAST_DEST"; then
  echo "==> ${APPCAST_DEST} already matches the released appcast; nothing to commit"
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
SUBJECT="chore(release): update appcast for v${VERSION}"
[ "$SKIP_CI" = "1" ] && SUBJECT="$SUBJECT [skip ci]"
git add -- "$APPCAST_DEST"
git commit --quiet -m "$SUBJECT" -m "Generated by release.yml for the v${VERSION} release and deployed to https://pasta-app.com/appcast.xml; committed back so the copy in git matches the live feed."
echo "==> $(git log --oneline -1)"

if git push --quiet origin "HEAD:${TARGET_BRANCH}" 2>"$WORK_DIR/push.err"; then
  echo "==> Pushed to ${TARGET_BRANCH}"
  exit 0
fi
echo "    direct push to ${TARGET_BRANCH} rejected: $(tail -1 "$WORK_DIR/push.err" | sed -E 's#https://[^@]+@#https://***@#')"

FALLBACK="release/appcast-v${VERSION}"
if ! git push --quiet --force origin "HEAD:refs/heads/${FALLBACK}" 2>"$WORK_DIR/push2.err"; then
  warn "could not push ${TARGET_BRANCH} or ${FALLBACK}: $(tail -1 "$WORK_DIR/push2.err" | sed -E 's#https://[^@]+@#https://***@#'). Copy the released appcast into ${APPCAST_DEST} by hand."
  exit 0
fi
PR_URL=""
if command -v gh >/dev/null 2>&1 && [ -n "${GH_TOKEN:-}" ] && [ -n "${GITHUB_REPOSITORY:-}" ]; then
  PR_URL="$(gh pr create --repo "$GITHUB_REPOSITORY" --base "$TARGET_BRANCH" --head "$FALLBACK" \
      --title "$SUBJECT" --body "Automated: release.yml could not push the regenerated appcast for v${VERSION} to ${TARGET_BRANCH} directly (branch protection). Merge so landing-page/appcast.xml matches the live feed." 2>/dev/null || true)"
fi
if [ -n "$PR_URL" ]; then
  warn "${TARGET_BRANCH} refused a direct push; opened ${PR_URL} — merge it so the git appcast matches the live feed."
else
  warn "${TARGET_BRANCH} refused a direct push; pushed branch ${FALLBACK} — open and merge a PR from it so the git appcast matches the live feed."
fi
exit 0
