import Foundation
import Combine
import os.log

#if canImport(AppKit)
import AppKit
#endif

public enum PasteboardContents: Equatable {
    case text(String)
    case rtf(String)
    case image(Data)
    case filePaths([String])
}

public struct PasteboardMetadata: Equatable {
    /// Whether the clipboard contents came from another device via Universal Clipboard/Handoff
    public let isContinuitySync: Bool
    /// The origin device name if available
    public let originDeviceName: String?
    
    public init(isContinuitySync: Bool = false, originDeviceName: String? = nil) {
        self.isContinuitySync = isContinuitySync
        self.originDeviceName = originDeviceName
    }
}

public protocol PasteboardProviding {
    var changeCount: Int { get }
    func readContents() -> PasteboardContents?
    func readMetadata() -> PasteboardMetadata
    /// Returns true when the current pasteboard is marked transient/concealed/auto-generated
    /// (e.g. password manager output) and must NOT be persisted.
    func isTransient() -> Bool
}

public extension PasteboardProviding {
    // Default no-op so existing conformers (mocks, tests) keep compiling.
    func isTransient() -> Bool { false }
}

/// Pasteboard type identifiers (from http://nspasteboard.org and Apple internal markers)
/// that signal the contents should be treated as transient and never recorded.
public enum TransientPasteboardType {
    public static let identifiers: Set<String> = [
        // nspasteboard.org community standard
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        // Apple-internal sensitivity markers
        "com.apple.is-sensitive",
        // Common password manager declared types
        "com.agilebits.onepassword",
        "com.1password.1password.private"
    ]

    public static func contains(_ types: [String]) -> Bool {
        for t in types where identifiers.contains(t) { return true }
        return false
    }
}

public protocol WorkspaceProviding {
    func frontmostApplicationIdentifier() -> String?
}

#if canImport(AppKit)
public struct SystemPasteboard: PasteboardProviding {
    private let pasteboard: NSPasteboard
    
    // Pasteboard types that indicate Universal Clipboard / Handoff
    private static let handoffTypes: Set<String> = [
        "com.apple.is-remote-clipboard",
        "com.apple.remote-clipboard.data",
        "dyn.age8u"  // Dynamic type used for Handoff
    ]

    public init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    public var changeCount: Int { pasteboard.changeCount }

    public func readContents() -> PasteboardContents? {
        // Check for file paths first (copying files in Finder)
        if let objects = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !objects.isEmpty {
            return .filePaths(objects.map { $0.path })
        }

        // Check for text content (RTF or plain text)
        // Do this BEFORE images because apps like Excel/Word include thumbnail images
        // alongside text, and we want to capture the text, not the preview image
        if let rtfData = pasteboard.data(forType: .rtf),
           let attributed = try? NSAttributedString(data: rtfData, options: [.documentType: NSAttributedString.DocumentType.rtf], documentAttributes: nil) {
            return .rtf(attributed.string)
        }

        if let string = pasteboard.string(forType: .string) {
            return .text(string)
        }

        // Only treat as image if no text content is available
        if let data = pasteboard.data(forType: .tiff) {
            return .image(data)
        }

        return nil
    }
    
    public func isTransient() -> Bool {
        let types = pasteboard.types?.map { $0.rawValue } ?? []
        return TransientPasteboardType.contains(types)
    }

    public func readMetadata() -> PasteboardMetadata {
        // Check if clipboard contains markers indicating it came from another device
        let types = pasteboard.types ?? []
        let typeStrings = Set(types.map { $0.rawValue })
        
        let isContinuity = !typeStrings.isDisjoint(with: Self.handoffTypes) ||
            typeStrings.contains(where: { $0.contains("remote") || $0.contains("handoff") })
        
        // Try to get origin device name from pasteboard data
        var deviceName: String? = nil
        if isContinuity {
            // Apple doesn't expose device name directly, but we can mark it as synced
            deviceName = "Another device"
        }
        
        return PasteboardMetadata(isContinuitySync: isContinuity, originDeviceName: deviceName)
    }
}

public struct SystemWorkspace: WorkspaceProviding {
    private let workspace: NSWorkspace

    public init(workspace: NSWorkspace = .shared) {
        self.workspace = workspace
    }

    public func frontmostApplicationIdentifier() -> String? {
        workspace.frontmostApplication?.bundleIdentifier ?? workspace.frontmostApplication?.localizedName
    }
}
#endif

public final class ClipboardMonitor {
    public var publisher: AnyPublisher<ClipboardEntry, Never> {
        subject.eraseToAnyPublisher()
    }

    /// Fingerprint of the last emitted contents, kept instead of the contents
    /// themselves so a copied image's bytes (20–100 MB for Retina screenshots)
    /// are never retained between polls.
    enum ContentFingerprint: Equatable {
        case text(String)
        case rtf(String)
        case filePaths([String])
        case imageHash(String)

        init(_ contents: PasteboardContents) {
            switch contents {
            case .text(let string): self = .text(string)
            case .rtf(let string): self = .rtf(string)
            case .filePaths(let paths): self = .filePaths(paths)
            case .image(let data): self = .imageHash(ClipboardEntry.sha256Hex(data))
            }
        }
    }

    private let pasteboard: PasteboardProviding
    private let workspace: WorkspaceProviding?
    private let exclusionManager: ExclusionManager
    private let tickPublisher: AnyPublisher<Void, Never>
    private let now: () -> Date
    private let respectTransientPasteboard: () -> Bool

    private let subject = PassthroughSubject<ClipboardEntry, Never>()
    private var cancellable: AnyCancellable?

    private var lastSeenChangeCount: Int?

    /// Serial queue on which pasteboard contents are read and deduplicated, so
    /// large RTF parses and TIFF copies never block the polling (main) thread.
    private let readQueue = DispatchQueue(label: "com.pasta.clipboard-read", qos: .userInitiated)
    /// Confined to `readQueue`.
    private var lastEmittedFingerprint: ContentFingerprint?

    /// Test hook: the current dedup fingerprint, read on the read queue.
    var currentFingerprintForTesting: ContentFingerprint? {
        readQueue.sync { lastEmittedFingerprint }
    }

    public init(
        pasteboard: PasteboardProviding,
        workspace: WorkspaceProviding? = nil,
        exclusionManager: ExclusionManager = ExclusionManager(),
        pollInterval: TimeInterval = 0.5,
        tickPublisher: AnyPublisher<Void, Never>? = nil,
        now: @escaping () -> Date = Date.init,
        respectTransientPasteboard: @escaping () -> Bool = {
            UserDefaults.standard.object(forKey: "pasta.respectTransientPasteboard") as? Bool ?? true
        }
    ) {
        self.pasteboard = pasteboard
        self.workspace = workspace
        self.exclusionManager = exclusionManager
        self.now = now
        self.respectTransientPasteboard = respectTransientPasteboard

        if let tickPublisher {
            self.tickPublisher = tickPublisher
        } else {
            self.tickPublisher = Timer
                .publish(every: pollInterval, on: .main, in: .common)
                .autoconnect()
                .map { _ in () }
                .eraseToAnyPublisher()
        }
    }

    #if canImport(AppKit)
    public convenience init(pollInterval: TimeInterval = 0.5) {
        self.init(pasteboard: SystemPasteboard(), workspace: SystemWorkspace(), exclusionManager: ExclusionManager(), pollInterval: pollInterval)
    }
    #endif

    public func start() {
        guard cancellable == nil else { return }
        lastSeenChangeCount = pasteboard.changeCount

        cancellable = tickPublisher
            .sink { [weak self] _ in
                self?.pollOnce()
            }
    }

    public func stop() {
        cancellable?.cancel()
        cancellable = nil
    }

    private func pollOnce() {
        let changeCount = pasteboard.changeCount
        if let lastSeenChangeCount, changeCount == lastSeenChangeCount { return }
        lastSeenChangeCount = changeCount

        // Privacy: skip transient/concealed clipboards (password managers, etc.)
        // Check BEFORE reading contents so we never even materialize the secret.
        // User can opt out via the "Respect transient pasteboard" Security setting.
        let respectTransient = respectTransientPasteboard()
        if respectTransient, pasteboard.isTransient() {
            PastaLogger.clipboard.debug("Skipped transient/concealed pasteboard contents")
            return
        }

        // Sample copy-time context on the polling thread: the frontmost app
        // must be whichever app the user copied from, not whatever is
        // frontmost once the read finishes.
        let sourceApp = workspace?.frontmostApplicationIdentifier()
        let timestamp = now()

        // The actual contents read (RTF parsing, multi-MB TIFF copies) happens
        // off the polling thread so large copies never hitch the UI.
        readQueue.async { [weak self] in
            self?.readAndEmit(expectedChangeCount: changeCount, sourceApp: sourceApp, timestamp: timestamp)
        }
    }

    /// Runs on `readQueue`.
    private func readAndEmit(expectedChangeCount: Int, sourceApp: String?, timestamp: Date) {
        guard let contents = pasteboard.readContents() else {
            // If we can't read the clipboard, it might be an access issue
            PastaLogger.clipboard.warning("Failed to read clipboard contents - may be access denied")
            return
        }

        // Check for Continuity clipboard
        let metadata = pasteboard.readMetadata()

        // The pasteboard may have changed while the read was in flight. Drop
        // the stale read: the poll loop has already seen (or will see) the new
        // changeCount and issue a fresh read for the current contents.
        guard pasteboard.changeCount == expectedChangeCount else {
            PastaLogger.clipboard.debug("Pasteboard changed during read; discarding stale contents")
            return
        }

        let fingerprint = ContentFingerprint(contents)
        if fingerprint == lastEmittedFingerprint { return }
        lastEmittedFingerprint = fingerprint

        if exclusionManager.isExcluded(bundleIdentifier: sourceApp) {
            PastaLogger.clipboard.debug("Skipped entry from excluded app: \(sourceApp ?? "unknown")")
            return
        }

        var entryMetadata: String? = nil
        if metadata.isContinuitySync {
            // Encode metadata as JSON
            let metaDict: [String: Any] = [
                "continuitySync": true,
                "originDevice": metadata.originDeviceName ?? "Unknown device"
            ]
            if let jsonData = try? JSONSerialization.data(withJSONObject: metaDict),
               let jsonString = String(data: jsonData, encoding: .utf8) {
                entryMetadata = jsonString
            }
            PastaLogger.clipboard.info("Detected Continuity clipboard sync from \(metadata.originDeviceName ?? "another device")")
        }

        let entry = ClipboardEntry(
            content: contentString(for: contents),
            contentType: contentType(for: contents, sourceApp: sourceApp),
            rawData: rawData(for: contents),
            timestamp: timestamp,
            sourceApp: metadata.isContinuitySync ? "Continuity" : sourceApp,
            metadata: entryMetadata
        )

        DispatchQueue.main.async { [weak self] in
            guard let self, self.cancellable != nil else { return }
            PastaLogger.clipboard.debug("Captured clipboard entry of type \(entry.contentType.rawValue)")
            self.subject.send(entry)
        }
    }

    private func contentType(for contents: PasteboardContents, sourceApp: String?) -> ContentType {
        switch contents {
        case .text, .rtf:
            return .text
        case .image:
            // Detect screenshots by source app
            if let app = sourceApp?.lowercased(),
               app.contains("screenshot") || app.contains("screencapture") {
                return .screenshot
            }
            return .image
        case .filePaths:
            return .filePath
        }
    }

    private func contentString(for contents: PasteboardContents) -> String {
        switch contents {
        case .text(let string), .rtf(let string):
            return string
        case .image:
            return ""
        case .filePaths(let paths):
            return paths.joined(separator: "\n")
        }
    }

    private func rawData(for contents: PasteboardContents) -> Data? {
        switch contents {
        case .image(let data):
            return data
        case .text, .rtf, .filePaths:
            return nil
        }
    }
}
